import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" scroll-behavior = "smooth"
    
    >
      <link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
  integrity="sha384-k6RqeWeci5ZR/Lv4MR0sA0FfDOMS0IJcxzqxOCY1MJY93CuN5ghg2LOQqT2EYm+"
  crossOrigin="anonymous"
/>

      
      <body>
          <img  
        className="fixed inset-0 w-full h-full object-none z-[-1]"
        src = './images/background1.jpg' 
        alt = "Background"
        />
        
        <script src="https://kit.fontawesome.com/7ed0d034af.js"></script>
          
          {children}
      </body>
    </html> 
  );
}
